### ISSUE TITLE
Latest tags for JDK 9 missing

### ISSUE THREAD

**Issue by gunnarmorling** [unofficial-openjdk/openjdk#1]
Hi David, looking in the tags, I couldn't find the latest ones for JDK 9 (latest I see is b94).

**Comment by dmlloyd** [comment]
The naming convention changed at this point; look for jdk-9+95 through jdk-9+140.

**Comment by gunnarmorling** [comment]
Hum, weird, indeed I can go to tag via its URL directly, e.g. https://github.com/dmlloyd/openjdk/tree/jdk-9+140, but these tags don't show up in the tags drop down for me (neither are they returned when typing into "Find a tag...").

**Comment by dmlloyd** [comment]
Maybe GitHub has a bug where they don't escape "+" which of course has special meaning in a URL..
