### ISSUE TITLE
why I should install Bootstrap JDK first brfore make openjdk?

### ISSUE THREAD

**Issue by hustguobing** [unofficial-openjdk/openjdk#20]
为什么要有一个引导jdk之后才能编译openjdk?

**Comment by Maxatom** [comment]
Yes，because most of the code is wirrten in java. so you need a Bootstrap JDK to compile them.

**Comment by dmlloyd** [comment]
This is just a mirror of OpenJDK.  There are many better places to ask questions about it.  Maybe try StackOverflow, or one of the JDK mailing lists.
